/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Comments {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  postId: number;
  updated_at: Timestamp | null;
  userId: number;
}

export interface Posts {
  authorId: number;
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  title: string;
  updatedAt: Timestamp | null;
}

export interface PostTags {
  postId: number;
  tagId: number;
}

export interface Tags {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updatedAt: Timestamp | null;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
  updatedAt: Timestamp | null;
}

export interface DB {
  comments: Comments;
  posts: Posts;
  postTags: PostTags;
  tags: Tags;
  users: Users;
}
